config/routes.rb
Rails.application.routes.draw do
  match 'surveys', :to                                      => 'surveyor#new', :as    => 'available_surveys', :via => :get
  match 'surveys/:survey_code', :to                         => 'surveyor#create', :as => 'take_survey', :via       => :post
  match 'surveys/:survey_code', :to                    => 'surveyor#export', :as => 'export_survey', :via     => :get
  match 'surveys/:survey_code/:response_set_code', :to      => 'surveyor#show', :as   => 'view_my_survey', :via    => :get
  match 'surveys/:survey_code/:response_set_code/take', :to => 'surveyor#edit', :as   => 'edit_my_survey', :via    => :get
  match 'surveys/:survey_code/:response_set_code', :to      => 'surveyor#update', :as => 'update_my_survey', :via  => :put
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  unloadable
  include Surveyor::Models::AnswerMethods
end

app/models/dependency.rb
class Dependency < ActiveRecord::Base
  unloadable
  include Surveyor::Models::DependencyMethods
end

app/models/dependency_condition.rb
class DependencyCondition < ActiveRecord::Base
  unloadable
  include Surveyor::Models::DependencyConditionMethods
end

app/models/question.rb
class Question < ActiveRecord::Base
  unloadable
  include Surveyor::Models::QuestionMethods
end

app/models/question_group.rb
class QuestionGroup < ActiveRecord::Base
  unloadable
  include Surveyor::Models::QuestionGroupMethods
  
end

app/models/response.rb
class Response < ActiveRecord::Base
  unloadable
  include ActionView::Helpers::SanitizeHelper
  include Surveyor::Models::ResponseMethods
end

app/models/response_set.rb
class ResponseSet < ActiveRecord::Base
  unloadable
  include Surveyor::Models::ResponseSetMethods
end

app/models/survey.rb
class Survey < ActiveRecord::Base
  unloadable
  include Surveyor::Models::SurveyMethods  
end

app/models/survey_section.rb
class SurveySection < ActiveRecord::Base
  unloadable
  include Surveyor::Models::SurveySectionMethods
end

app/models/survey_section_sweeper.rb
class SurveySectionSweeper < ActionController::Caching::Sweeper
  observe :survey_section
  
  def after_save(section)
    expire_cache(section)
  end
  
  def after_destroy(section)
    expire_cache(section)
  end
  
  def expire_cache(section)
    expire_fregment "section_#{section.id}"
  end
end

app/models/validation.rb
class Validation < ActiveRecord::Base
  unloadable
  include Surveyor::Models::ValidationMethods
end

app/models/validation_condition.rb
class ValidationCondition < ActiveRecord::Base
  unloadable
  include Surveyor::Models::ValidationConditionMethods
end

app/controllers/surveyor_controller.rb
# Surveyor Controller allows a user to take a survey. It is semi-RESTful since it does not have a concrete representation model.
# The "resource" is a survey attempt/session populating a response set.
class SurveyorController < ApplicationController
  unloadable
  include Surveyor::SurveyorControllerMethods
end

app/helpers/results_helper.rb
module ResultsHelper
  def display_response(r_set,question)
    sets = r_set.responses.select{|r| r.question.display_order == question.display_order}
	  	if sets.size == 0
  			return "-"
  		elsif sets.size == 1
  			return (sets.first.string_value || sets.first.text_value || show_answer(sets.first))
  		else
  		  txt = ""
        sets.each do |set|
          txt << show_answer(set) + "<br/>"
        end
        return txt
		  end
  end
  
  def show_answer(set)
     set.answer.text
  end
end

app/helpers/survey_form_builder.rb
class SurveyFormBuilder < ActionView::Helpers::FormBuilder 
  def survey_check_box(method, options = {}, checked_value = "1", unchecked_value = "0")
    fields = @template.survey_check_box(@object_name, method, options.merge(:object => @object), checked_value, unchecked_value)
    fields[1]
  end
end

module ActionView
  module Helpers
    module FormHelper
      def survey_check_box(object_name, method, options = {}, checked_value = "1", unchecked_value = "0")
        if (Rails::VERSION::STRING.to_f > 2.1)
          InstanceTag.new(object_name, method, self, options.delete(:object)).to_survey_check_box_tag(options, checked_value, unchecked_value)
        else
          InstanceTag.new(object_name, method, self, nil, options.delete(:object)).to_survey_check_box_tag(options, checked_value, unchecked_value)
        end
      end
    end

    class InstanceTag
      def to_survey_check_box_tag(options = {}, checked_value = "1", unchecked_value = "0")
        options = options.stringify_keys
        options["type"]     = "checkbox"
        options["value"]    = checked_value
        if options.has_key?("checked")
          cv = options.delete "checked"
          checked = cv == true || cv == "checked"
        else
          checked = self.class.check_box_checked?(value(object), checked_value)
        end
        options["checked"] = "checked" if checked
        add_default_name_and_id(options)
        [tag("input", "name" => options["name"], "type" => "hidden", "value" => unchecked_value), tag("input", options)]
      end
    end
  end
end

app/helpers/surveyor_helper.rb
module SurveyorHelper
  include Surveyor::Helpers::SurveyorHelperMethods
end

app/views/layouts/results.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
  <title>Survey: Result Sets</title>
  <%= surveyor_includes %>
</head>
<body>
  <div id="flash"><%= flash[:notice] %></div>
  <%= yield %>
</body>
</html>

app/views/layouts/surveyor_default.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
  <title>Survey: <%= controller.action_name %></title>
  <%= surveyor_includes %>
</head>
<body>
  <%= yield %>
</body>
</html>

app/views/partials/_answer.html.haml
-# TODO: disabled
- rg ||= nil
- r = response_for(@response_set, q, a, rg)
- i = response_idx(q.pick != "one") # argument will be false (don't increment i) if we're on radio buttons
- disabled = defined?(disableFlag) ? disableFlag : false
= f.semantic_fields_for i, r do |ff|
  = ff.quiet_input :question_id unless q.pick == "one" # don't repeat question_id if we're on radio buttons
  = ff.quiet_input :id unless q.pick == "one" or r.new_record?
  = ff.quiet_input :response_group, :value => rg if q.pick != "one" && g && g.display_type == "repeater"
  - case q.pick
  - when "one"
    = ff.input :answer_id, :as => :surveyor_radio, :collection => [[a_text(a, nil, @render_context), a.id]], :label => false, :input_html => {:class => a.css_class, :disabled => disabled}, :response_class => a.response_class
  - when "any"
    = ff.input :answer_id, :as => :surveyor_check_boxes, :collection => [[a_text(a, nil, @render_context), a.id]], :label => false, :input_html => {:class => a.css_class, :disabled => disabled}, :response_class => a.response_class
  - when "none"
    - if %w(date datetime time float integer string text).include? a.response_class
      = ff.quiet_input :answer_id, :input_html => {:class => a.css_class, :value => a.id}
      = ff.input rc_to_attr(a.response_class), :as => rc_to_as(a.response_class), :label => a_text(a, :pre, @render_context).blank? ? false : a_text(a, :pre, @render_context), :hint => a_text(a, :post, @render_context), :input_html => generate_pick_none_input_html(r.as(a.response_class), a.default_value, a.css_class, a.response_class, disabled)
    - else
      = a_text(a, nil, @render_context)

app/views/partials/_dependents.html.haml
#dependents
  .title Follow-up questions from your answers on the previous page
  -# @dependents.each_with_index do |question, index|
    = dependency_explanation_helper(question, @response_set)
    = render question.custom_renderer || "/partials/question", :question => question, :response_set => @response_set, :number => "D#{index+1}"

app/views/partials/_question.html.haml
-# TODO: js for slider
- rg ||= nil
- renderer = q.renderer(g ||= nil)
- disabled = defined?(disableFlag) ? disableFlag : false
= f.inputs q_text(q, @render_context), :id => rg ? "q_#{q.id}_#{rg}" : "q_#{q.id}", :class => "q_#{renderer} #{q.css_class(@response_set)}" do
  %span.help= render_help_text(q, @render_context)
  - case renderer
  - when :image, :label
  - when :dropdown, :inline_dropdown, :default_dropdown, :slider, :repeater_dropdown
    - r = response_for(@response_set, q, nil, rg)
    - i = response_idx
    = f.semantic_fields_for i, r do |ff|
      = ff.quiet_input :question_id
      = ff.quiet_input :response_group, :value => rg if g && g.display_type == "repeater"
      = ff.quiet_input :id unless r.new_record?
      = ff.input :answer_id, :as => :select, :collection => q.answers.map{|a| [a.text, a.id]}, :label => q.text, :input_html => { :disabled => disabled }
  - else # :default, :inline, :inline_default
    - if q.pick == "one"
      - r = response_for(@response_set, q, nil, rg)
      - i = response_idx  # increment the response index since the answer partial skips for q.pick == one
      = f.semantic_fields_for i, r do |ff|
        = ff.quiet_input :question_id
        = ff.quiet_input :response_group, :value => rg if g && g.display_type == "repeater"
        = ff.quiet_input :id unless r.new_record?
    - q.answers.each do |a|
      - next if (q.pick == "one" or q.pick == "any") and disabled and @response_set.responses.where( :question_id => q.id, :answer_id => a.id).empty? 
      = render a.custom_renderer || '/partials/answer', :q => q, :a => a, :f => f, :rg => rg, :g => g, :disableFlag => disabled

app/views/partials/_question_group.html.haml
- renderer = g.renderer
= f.inputs q_text(g, @render_context), :id => "g_#{g.id}", :class => "g_#{renderer} #{g.css_class(@response_set)}" do
  %li.help= render_help_text(g, @render_context)
  - case renderer
    - when :grid
      %li
        %table
          %col.pre
          - qs.first.answers.each do |a| 
            %col{:class => cycle("odd", "even")}
          %col.post
          %tbody
            - qs.each_slice(10) do |ten_questions| # header row every 10
              %tr
                %th &nbsp;
                - ten_questions.first.answers.each do |a|
                  %th= a_text(a)
                %th &nbsp;
              - ten_questions.each_with_index do |q, i|
                %tr{:id => "q_#{q.id}", :class => "q_#{renderer} #{q.css_class(@response_set)}"}
                  - if q.pick == "one"
                    - r = response_for(@response_set, q, nil, g)
                    - i = response_idx  # increment the response index since the answer partial skips for q.pick == one
                    = f.semantic_fields_for i, r do |ff|
                      = ff.quiet_input :question_id
                      = ff.quiet_input :id unless r.new_record?
                  %th= q.split_text(:pre)
                  - q.answers.each do |a|
                    %td= render a.custom_renderer || '/partials/answer', :g => g, :q => q, :a => a, :f => f
                  %th= q.split_text(:post)
    - when :repeater
      - (@response_set.count_group_responses(qs) + 1).times do |rg|
        %li
          - qs.each do |q|
            = render q.custom_renderer || "/partials/question", :g => g, :rg => rg, :q => q, :f => f
      = submit_tag("+ add row", :name => "section[#{@section.id}][g_#{g.id}]", :class => "add_row")
    - else # :inline
      - qs.each do |q|
        = render q.custom_renderer || "/partials/question", :g => g, :q => q, :f => f

app/views/partials/_section.html.haml
= div_for @section, :class => @section.custom_class do
  %span.title= @section.title
  - qs ||= []
  - (questions = @section.questions).each_with_index do |q, i|
    - if q.part_of_group?
      - qs << q # gather up the group questions
      - if (i+1 >= questions.size) or (q.question_group_id != questions[i+1].question_group_id)
        - # this is the last question of the section, or the group
        = render q.question_group.custom_renderer || "/partials/question_group", :g => q.question_group, :qs => qs, :f => f
        - qs = []
    - else # gather up the group questions
      = render q.custom_renderer || "/partials/question", :q => q, :f => f

app/views/partials/_section_menu.html.haml
.surveyor_menu
  = t('surveyor.sections')
  %ul
    - @sections.each do |s|
      %li{:class => ("active" if s == @section)}= menu_button_for(s)

app/views/surveyor/edit.html.haml
#surveyor
  - unless (types = flash.keys.select{|k| [:notice, :error, :warning].include?(k)}).blank?
    .surveyor_flash
      = flash_messages(types)
      .close
  = semantic_form_for(@response_set, :as => :r, :url => update_my_survey_path, :html => {:method => :put, :id => "survey_form", :class => @survey.custom_class}) do |f|
  
    = hidden_field_tag :surveyor_javascript_enabled, false
  
    = render 'partials/section_menu' # unless @sections.size < 3
    .survey_title= @survey.title
    .previous_section= previous_section
    = render 'partials/dependents' unless @dependents.empty?
    - if false #@response_set.no_responses_for_section?(@section) # cache if response_set has no responses for current section
      = cache("section_#{@section.id}"){ render "/partials/section", :f => f }
    - else # no cache
      = render "/partials/section", :f => f
    .next_section= next_section
  %br

:javascript
  $(document).ready(function() {
    $("input#surveyor_javascript_enabled").val(true);
  });

app/views/surveyor/new.html.haml
#surveyor
  - unless (types = flash.keys.select{|k| [:notice, :error, :warning].include?(k)}).blank?
    .surveyor_flash
      = flash_messages(types)
      .close
  .survey_title= t('surveyor.take_these_surveys')
  %br
  #survey_list
    %ul
      - unless @surveys.empty?
        - @surveys.each do |survey|
          %li
            = form_tag(take_survey_path(:survey_code => survey.access_code)) do 
              = hidden_field_tag :surveyor_javascript_enabled, false              

              = survey.title
              &nbsp;
              = submit_tag( t('surveyor.take_it') )
      - else
        %li
          No surveys

:javascript
  $(document).ready(function() {
    $("input#surveyor_javascript_enabled").val(true);
  });

app/views/surveyor/show.html.haml
#surveyor
  - unless (types = flash.keys.select{|k| [:notice, :error, :warning].include?(k)}).blank?
    .surveyor_flash
      = flash_messages(types)
      .close
  = semantic_form_for(@response_set, :as => :r, :url => update_my_survey_path, :html => {:id => "survey_form", :class => @survey.custom_class}) do |f|
    .survey_title= @survey.title
    - @survey.sections.each do |section|
      = div_for section do
        %span.title= strip_tags(section.title)
        - group_questions = []
        - answered_questions = []
        - label = nil
        - answered_count = 0
        - (questions = section.questions).each_with_index do |q, i|
          - if q.part_of_group?
            - group_questions << q # gather up the group questions
            - unless @response_set.responses.where( :question_id => q.id).empty?
              - answered_questions << q
              - answered_count = answered_count + 1
            - if (i+1 >= questions.size) or (q.question_group_id != questions[i+1].question_group_id) # this is the last question of the section, or the group
              - if answered_questions.length > 0 # there are answered questions in this section or group
                - g = q.question_group
                - renderer = g.renderer
                
                - unless label.blank?
                  = render q.custom_renderer || "/partials/question", :q => label, :f => f, :disableFlag => true
                  - label = nil
                = f.inputs q_text(g), :id => "g_#{g.id}", :class => "g_#{renderer} #{g.css_class(@response_set)}" do
                  %li.help= g.help_text
                  - case renderer
                    - when :grid
                      %li
                        %table
                          %col.pre
                          - group_questions.first.answers.each do |a| 
                            %col{:class => cycle("odd", "even")}
                          %col.post
                          %tbody
                            - group_questions.each_slice(10) do |ten_questions| # header row every 10
                              %tr
                                %th &nbsp;
                                - ten_questions.first.answers.each do |a|
                                  %th= a_text(a)
                                %th &nbsp;
                              - ten_questions.each_with_index do |q, j|
                                %tr{:id => "q_#{q.id}", :class => "q_#{renderer} #{q.css_class(@response_set)}"}
                                  - if q.pick == "one"
                                    - r = response_for(@response_set, q, nil, g)
                                    - j = response_idx  # increment the response index since the answer partial skips for q.pick == one
                                  %th= q.split_text(:pre)
                                  - q.answers.each do |a|
                                    %td= render a.custom_renderer || '/partials/answer', :g => g, :q => q, :a => a, :f => f, :disableFlag => true
                                  %th= q.split_text(:post)
                    - when :repeater
                      - (@response_set.count_group_responses(group_questions) + 1).times do |rg|
                        %li
                          - group_questions.each do |q|
                            = render q.custom_renderer || "/partials/question", :g => g, :rg => rg, :q => q, :f => f, :disableFlag => true
                    - else # :inline
                      - answered_questions.each do |q|
                        = render q.custom_renderer || "/partials/question", :g => g, :q => q, :f => f, :disableFlag => true         
              
              - group_questions = []
              - answered_questions = []
          - else 
            - if q.display_type == 'label'
              - label = q
            - unless @response_set.responses.where( :question_id => q.id).empty?
              - unless label.blank?
                = render q.custom_renderer || "/partials/question", :q => label, :f => f, :disableFlag => true
                - label = nil
              = render q.custom_renderer || "/partials/question", :q => q, :f => f, :disableFlag => true
              - answered_count = answered_count + 1
          - if (i+1 >= questions.size) and (answered_count == 0)
            #{"--- No data ---"}
          